#!/bin/sh
XX_NPM=

if [ ! -f "package.json" ]; then
    echo "fetal: not a nodejs project"
    echo
    exit 1
fi

# NPM
if [ -f ".npmrc" ] || [ -f "package-lock.json" ]; then
    XX_NPM=npm
fi

# Yarn
if [ -f ".yarnrc" ] || [ -f "yarn.lock" ]; then
    XX_NPM=yarn
fi

# PNPM
if [ -f ".pnpmfile.cjs" ] || [ -f "pnpm-workspace.yaml" ] || [ -f "pnpm-lock.yaml" ]; then
    XX_NPM=pnpm
fi

if [ ! "$(command -v $XX_NPM)" ]; then
    echo "fetal: command \"$XX_NPM\" exists on system"
    exit 1
fi

echo "xx-npm: using ${XX_NPM} as package manager"
echo
export XX_NPM
exec ${XX_NPM} "$@"
